### ISSUE TITLE
Huh, something is not working

### ISSUE THREAD

**Issue by igr** [LWJGL/lwjgl3-gradle#1]
```
plugins {
    id('org.jetbrains.kotlin.jvm')
    id("org.lwjgl.plugin") version "0.0.20"
}
dependencies {

    Lwjgl { implementation(Preset.everything) }
}
```

it is not recognized

```
 Could not find method Lwjgl() for arguments [build_47r8pcqtz5jnglf4effz199kk$_run_closure1$_closure2@30d33f8b] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
```

**Comment by elect86** [comment]
Which language are you using?

**Comment by igr** [comment]
it was kotlin, but above snippet is gradle.

**Comment by elect86** [comment]
Is the project public?

**Comment by igr** [comment]
Nope, tried locally. Don't have it anymore, as I imported all dependencies manually.

**Comment by igr** [comment]
I was also using groovy gradle (not kotlin variant)

**Comment by elect86** [comment]
As I imagined.. I didn't test with Groovy, I think I have to resort using Gradle Action for that

If you still available for testing we might try that together, if you want

**Comment by igr** [comment]
I will come back to this, later this week

**Comment by alexaragao** [comment]
+1

**Comment by elect86** [comment]
@alexaragao wanna give it a try?

**Comment by alexaragao** [comment]
@elect86, I'm facing the this same error, but in a Java project. I'm using JDK 16 and gradle.

**Comment by elect86** [comment]
@alexaragao is it public?

**Comment by Kearny** [comment]
Hello, encountering the same error here with gradle (groovy) and java 17 (temurin).
I'm using the version "0.0.29"

**Comment by elect86** [comment]
Now both the `Could not find method Lwjgl` and the Groovy should be fixed now

Be sure to import the `lwjgl` function

`import org.lwjgl.lwjgl`

Let me know

**Comment by halotroop2288** [comment]
> Be sure to import the `lwjgl` function
> 
> `import org.lwjgl.lwjgl`

Doesn't seem to exist. (Using the latest version, which [doesn't seem to be consistent](https://mvnrepository.com/artifact/org.lwjgl.plugin/org.lwjgl.plugin.gradle.plugin?repo=gradle-plugins) [depending where you look for it](https://plugins.gradle.org/plugin/org.lwjgl.plugin), so please consider specifying a recommended repository in the README.)

```
unable to resolve class org.lwjgl.lwjgl
```

**Comment by elect86** [comment]
@halotroop2288 probably you have a old version, try to update

Feel free to reopen in case something isn't working yet

**Comment by halotroop2288** [comment]
> probably you have a old version, try to update

Yeah! I bet it's at least 2 months old at this point, considering you waited 2 months to reply.

It's irrelevant now though. The project files for whatever I was doing are long gone.

**Comment by elect86** [comment]
I'm sorry for that but I had/have many other priorities

If you are willing to contribute yourself to speed things up, don't hesitate to let me know and I'd be super glad to send you an invitation

**Comment by JuraSciix** [comment]
My solution for Groovy: 
```groovy

import org.lwjgl.Lwjgl


plugins {
    id 'java'
    id 'application'
    id 'org.lwjgl.plugin' version '0.0.34'
}

repositories {
    mavenCentral()
}

// Light-Weight Java Game Library
Lwjgl.INSTANCE.implementation(dependencies, [
        Lwjgl.Module.assimp,
        Lwjgl.Module.glfw,
        Lwjgl.Module.openal,
        Lwjgl.Module.opengl,
        Lwjgl.Module.stb
])
```

It helped me. I hope this helps you.
