### ISSUE TITLE
Invalid classifiers when "allNatives" is true.

### ISSUE THREAD

**Issue by aemogie** [LWJGL/lwjgl3-gradle#2]
I tried the plugin and it threw an error, after checking the source I found out that it's a bug -
The strings in the `allNative` list don't have the "`native-`" prefix, and it isn't prepended later when adding the dependency either.

https://github.com/LWJGL/lwjgl3-gradle/blob/4a5c30f1ca50210bd5a07375b2da2995c152d2d0/plugin/src/main/kotlin/org/lwjgl/lwjglUtil.kt#L132-L134
https://github.com/LWJGL/lwjgl3-gradle/blob/4a5c30f1ca50210bd5a07375b2da2995c152d2d0/plugin/src/main/kotlin/org/lwjgl/lwjglUtil.kt#L45-L48

**Comment by elect86** [comment]
This should be fixed now
