### ISSUE TITLE
Is this dead?

### ISSUE THREAD

**Issue by Flaflo** [LWJGL/lwjgl3-gradle#6]
Maybe putting this on archived or something similiar like putting info in the readme, because it is not supporting latest LWJGL

**Comment by elect86** [comment]
I can send you an invitation, so you can provide a PR, if you'd like 

I don't have time and it's not high on my list, unfortunately

**Comment by Flaflo** [comment]
> I can send you an invitation, so you can provide a PR, if you'd like 
> 
> I don't have time and it's not high on my list, unfortunately

Sure thing! Invite me and I'll look into it.

**Comment by HamiltonHuaji** [comment]
> Maybe putting this on archived or something similiar like putting info in the readme, because it is not supporting latest LWJGL

Are you still working on this repository?

**Comment by elect86** [comment]
It needs to be updated from time to time and I don't have anymore the capacity for that, if you want I can invite you as well
